---
title: "faxcrayon<br>dot art<br>`r emo::ji('fax')``r emo::ji('crayon')`"
output:
  html_document:
    theme:
      version: 4
---

```{css, echo=FALSE}
/* courier-prime-regular - latin */
@font-face {
  font-family: 'Courier Prime';
  font-style: normal;
  font-weight: 400;
  src: url('fonts/courier-prime-v2-latin-regular.eot'); /* IE9 Compat Modes */
  src: local(''),
       url('fonts/courier-prime-v2-latin-regular.eot?#iefix') format('embedded-opentype'), /* IE6-IE8 */
       url('fonts/courier-prime-v2-latin-regular.woff2') format('woff2'), /* Super Modern Browsers */
       url('fonts/courier-prime-v2-latin-regular.woff') format('woff'), /* Modern Browsers */
       url('fonts/courier-prime-v2-latin-regular.ttf') format('truetype'), /* Safari, Android, iOS */
       url('fonts/courier-prime-v2-latin-regular.svg#CourierPrime') format('svg'); /* Legacy iOS */
}

* { font-family: 'Courier Prime'; }

h1, h2, h3, h4, h5, h6, p {
  text-align: center;
}
```

```{r setup, echo=FALSE}
library(bs4cards)
```

<center>
<p>Recreational 'art' by [Matt Dray](https://www.matt-dray.com) made with [R](https://www.r-project.org/about.html)</p>
<p>[Source](https://www.github.com/matt-dray/faxcrayon) | [RMarkdown](https://rmarkdown.rstudio.com/) | [{bs4cards}](https://bs4cards.djnavarro.net/index.html) | [Courier Prime](https://fonts.google.com/specimen/Courier+Prime?category=Monospace&preview.text=faxcrayon.art&preview.text_type=custom) | [Pages](https://pages.github.com/)</p>
</center>

```{r card-groups, include=FALSE}
lmb_colours <- list(
  card(
    title = "londonmapbot 1",
    image = card_image(
      "https://www.rostrum.blog/post/2021-07-23-london-colour_files/figure-html/mosaic-random-1.png",
      alt = "A 25 by 25 grid of squares, each of which represents a random satellite image of Greater London that's been quantized to show one representative colour. This has resulted in various shades of grey, green and cream, depending on factors like urbanness and green space in the original satellite image. The arrangement of colours appears to be random.",
    ),
    text = "Original",
    link = "https://www.rostrum.blog/2021/07/23/london-colour/",
    header = "2021-07-24"
  ),
  card(
    title = "londonmapbot 2",
    image = card_image(
      "https://www.rostrum.blog/post/2021-07-23-london-colour_files/figure-html/mosaic-col-1.png",
      alt = "A 25 by 25 grid of squares, each of which represents a random satellite image of Greater London that's been quantized to show one representative colour. This has resulted in various shades of grey, green and cream, depending on factors like urbanness and green space in the original satellite image. The squares are ordered form brightest in the top-left to darkest in the lower-right."
    ),
    text = "Original",
    link = "https://www.rostrum.blog/2021/07/23/london-colour/",
    header = "2021-07-24"
  )
)

kierisi <- list(
  card(
    title = "Kierisi 1",
    image = card_image(
      "https://raw.githubusercontent.com/matt-dray/viz-recreation/main/2021-07-08_twitter_kierisi/output/kierisi-recreate.png",
      alt = "A composition of squares in a staggered cross shape, composed of coloured squares of four colours—a grey, a blue-grey, an orange and a yellow (colours approximate, since I'm colourblind)—on a white background."
    ),
    text = "Recreation",
    link = "https://github.com/matt-dray/viz-recreation/tree/main/2021-07-08_twitter_kierisi",
    header = "2021-07-08"
  )
)

lewitt <- list(
  
  card(
    title = "LeWitt 1",
    image = card_image(
      "https://www.rostrum.blog/post/2021-07-05-recreate-lewitt_files/figure-html/concentric-circles-1.png",
      alt = "Concentric circles coloured consecutively with colours of the rainbow."
    ),
    text = "Original",
    link = "https://github.com/matt-dray/viz-recreation/tree/main/2021-07-01_rt_lewitt",
    header = "2021-07-01"
  ),
  
  card(
    title = "LeWitt 2",
    image = card_image(
      "https://www.rostrum.blog/post/2021-07-05-recreate-lewitt_files/figure-html/single-panel-triangles-1.png",
      alt = "A square image with a black border that contains concentric triangles coloured consecutively with rainbow colours."
    ),
    text = "Remix",
    link = "https://github.com/matt-dray/viz-recreation/tree/main/2021-07-01_rt_lewitt",
    header = "2021-07-01"
  ),
  
  card(
    title = "LeWitt 3",
    image = card_image(
      "https://camo.githubusercontent.com/7e87fdd8c89d6f14cc0012190a0ee58a0b6f50d04d4af6b97382e5b46767a1ec/68747470733a2f2f7777772e726f737472756d2e626c6f672f706f73742f323032312d30372d30352d72656372656174652d6c65776974745f66696c65732f6669677572652d68746d6c2f6578616d706c652d31302d312d302d312e706e67",
      alt = "A square image containing 100 panels in a 10 by 10 grid. Each panel contains concentric patterns of squares, triangles or circles with an alternating randomised colour palette. There are no borders around each panel."
    ),
    text = "Remix",
    link = "https://github.com/matt-dray/viz-recreation/tree/main/2021-07-01_rt_lewitt",
    header = "2021-07-01"
  ),
  
  card(
    title = "LeWitt 4",
    image = card_image(
      "https://camo.githubusercontent.com/c7392c62313c695c33046485091da7df4de3332b6bb986cebe3abc8481c89db3/68747470733a2f2f7777772e726f737472756d2e626c6f672f706f73742f323032312d30372d30352d72656372656174652d6c65776974745f66696c65732f6669677572652d68746d6c2f6578616d706c652d322d342d31302d312e706e67",
      alt = "A square image containing four panels in a two by two grid. Each panel contains concentric patterns of squares, triangles or circles with an alternating randomised colour palette. Each panel has a thick black border around it."
    ),
    text = "Remix",
    link = "https://github.com/matt-dray/viz-recreation/tree/main/2021-07-01_rt_lewitt",
    header = "2021-07-01"
  ),
  
  card(
    title = "LeWitt 5",
    image = card_image(
    "https://www.rostrum.blog/post/2021-07-05-recreate-lewitt_files/figure-html/example-2-20-0-1.png",
    alt = "A square image containing four panels in a two by two grid. Each panel contains concentric patterns of squares, triangles or circles with an alternating randomised colour palette. The lines created by the concentric shapes appear thick. There are no borders around each panel."
    ),
    text = "Remix",
    link = "https://github.com/matt-dray/viz-recreation/tree/main/2021-07-01_rt_lewitt",
    header = "2021-07-01"
  ),
  
  card(
    title = "LeWitt 6",
    image = card_image(
      "https://www.rostrum.blog/post/2021-07-05-recreate-lewitt_files/figure-html/example-10-1-20-1.png",
      alt = "A square image containing 100 panels in a 10 by 10 grid. Each panel contains concentric patterns of squares, triangles or circles with an alternating randomised colour palette. The lines created by the concentric shapes appear thin. There are extremely thick black borders around each panel."
    ),
    text = "Remix",
    link = "https://github.com/matt-dray/viz-recreation/tree/main/2021-07-01_rt_lewitt",
    header = "2021-07-01"
  ),
  
  card(
    title = "LeWitt 7",
    image = card_image(
      "https://www.rostrum.blog/post/2021-07-05-recreate-lewitt_files/figure-html/example-2-0.4-0-1.png",
      alt = "A square image containing four panels in a two by two grid. Each panel contains concentric patterns of squares or circles with an alternating randomised colour palette. The lines created by the concentric shapes appear extremely thin. There are no borders around the panels. The patterns give a slight impression of motion, liek a moiré pattern."
    ),
    text = "Remix",
    link = "https://github.com/matt-dray/viz-recreation/tree/main/2021-07-01_rt_lewitt",
    header = "2021-07-01"
  )
  
)

link <- list(
  card(
    title = "Link 1",
    image = card_image(
      "https://raw.githubusercontent.com/matt-dray/viz-recreation/main/2021-06-28_pixel-art_various/output/link-recreate.gif",
      alt = "A two-frame walk-cycle animation of the 16 by 16 sprite of the character Link from The Legend of Zelda on the Nintendo Enterntainment System."
    ),
    text = "Recreation",
    link = "https://github.com/matt-dray/viz-recreation/tree/main/2021-06-28_pixel-art_various",
    header = "2021-06-28"
  )
)

# spear <- list(
#   card(
#     title = "Spear 0",
#     image = "https://raw.githubusercontent.com/matt-dray/viz-recreation/main/2021-06-08_cottonviz_spear/output/cottonviz-recreate.png",
#     text = "Recreation",
#     link = "https://github.com/matt-dray/viz-recreation/tree/main/2021-06-08_cottonviz_spear",
#     header = "2021-06-08"
#   ),
#   
#   card(
#     title = "Spear 1",
#     image = "https://raw.githubusercontent.com/matt-dray/viz-recreation/main/2021-06-08_cottonviz_spear/output/gif/recreate-cottonviz.gif",
#     text = "Recreation",
#     link = "https://github.com/matt-dray/viz-recreation/tree/main/2021-06-08_cottonviz_spear",
#     header = "2021-06-08"
#   ),
#   
#     card(
#     title = "Spear 2",
#     image = "https://raw.githubusercontent.com/matt-dray/viz-recreation/main/2021-06-08_cottonviz_spear/output/cottonviz-remix-neg.png",
#     text = "Remix",
#     link = "https://github.com/matt-dray/viz-recreation/tree/main/2021-06-08_cottonviz_spear",
#     header = "2021-06-08"
#   )
#   
# )

hlito <- list(
  card(
    title = "Hlito 1",
    image = card_image(
      "https://raw.githubusercontent.com/matt-dray/viz-recreation/main/2021-06-03_rt_hlito/output/recreate-hlito.png",
      alt = "A recreation of Curves and Straight Lines (1948) by Alfred Hlito, which is an oil painting of colorful geometric lines on a cream background. Starting at the top of the painting in the middle there is a dark yellow curve. Intersecting it in the center of the painting is a black line at a 45 degree angle and a dark blue curve. In the top right of the center area there are short horizontal black blue green and red lines. In the top left of the center area are horizontal green red blue and black lines. In the bottom left of the center there is a short horizontal red line."
    ),
    text = "Recreation",
    link = "https://github.com/matt-dray/viz-recreation/tree/main/2021-06-03_rt_hlito",
    header = "2021-06-03"
  ),
  
  card(
    title = "Hlito 2",
    image = card_image(
      "https://raw.githubusercontent.com/matt-dray/viz-recreation/main/2021-06-03_rt_hlito/output/remix-hlito-100.png",
      alt = "A recreation of Curves and Straight Lines (1948) by Alfred Hlito. This version is a 10 by 10 grid of reproductions of Hlito's original, where randomisation has been introduced into each panel to vary the length and placement of the elements: a horizontal black stripe, several short horizontal lines of various colours and two circles, one blue, one dark yellow; all on a cream background."
    ),
    text = "Remix",
    link = "https://github.com/matt-dray/viz-recreation/tree/main/2021-06-03_rt_hlito",
    header = "2021-06-03"
  ),
  
  card(
    title = "Hlito 3",
    image = card_image(
      "https://raw.githubusercontent.com/matt-dray/viz-recreation/main/2021-06-03_rt_hlito/output/gif/remix-hlito_max.gif",
      alt = "A recreation of Curves and Straight Lines (1948) by Alfred Hlito. This version is an animated gif where each frame is a new veresion of Hlito's original with randomisation that varies the length and placement of the elements: a horizontal black stripe, several short horizontal lines of various colours and two circles, one blue, one dark yellow; all on a cream background."
    ),
    text = "Remix",
    link = "https://github.com/matt-dray/viz-recreation/tree/main/2021-06-03_rt_hlito",
    header = "2021-06-03"
  )
  
)
```

```{r card-place, echo=FALSE}
card_list <- c(
  lmb_colours,
  kierisi,
  lewitt,
  link,
  # spear,
  hlito
)

card_grid(card_list)
```

<center>['art is dead'](https://www.youtube.com/watch?v=Eo9pU1q8sy8)</center>